from enum import Enum


class ErrorCode(Enum):
    SUCCESS = 0
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    METHOD_NOT_ALLOWED = 405
    NOT_ACCEPTABLE = 406
    UNSUPPORTED_MEDIA_TYPE = 415
    INTERNAL_ERR = 500
    SERVICE_UNAVAILABLE = 503
