scrape_configs:
  - job_name: "FastAPI Application"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "My FastAPI Application"
