name: FastAPI CI

on:
  push:
    branches: ["main"]
    paths:
      - src/app/**
  pull_request:
    branches: ["main"]
    paths:
      - src/app/**

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: Admin@123
          MYSQL_DATABASE: sample_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:7.2.1-alpine3.18
        env:
          REDIS_PASSWORD: Redis@123
        ports:
          - 6379:6379
      mongodb:
        image: mongodb/mongodb-community-server:7.0.1-ubuntu2204
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: Mongo@123
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh mongodb://localhost:27017 --eval \"db.runCommand({ ping: 1 })\"" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Import database mySQL
        run: |
          wget -O scripts.sql https://raw.githubusercontent.com/robert28893/java-coaching-lab/main/source/docker-compose/mysql/db-dumps/job_db.sql
          mysql -h 127.0.0.1 --port=3306 -u root -p"Admin@123" < scripts.sql
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Setup database and user in mongodb
        run: |
          npm install -g mongosh
          mongosh mongodb://127.0.0.1:27017 -u root -p Mongo@123 --eval "use sample_db;" --eval "db.createUser({user: 'user', pwd: 'User123', roles : [{role: 'dbOwner', db: 'sample_db'}]});"

      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # - name: Run Tests
      #   env:
      #     DATASOURCE_URL: "jdbc:mysql://127.0.0.1:3306/sample_db"
      #     DATASOURCE_USERNAME: "root"
      #     DATASOURCE_PASSWORD: "Admin@123"
      #     REDIS_HOST: "127.0.0.1"
      #     REDIS_PORT: "6379"
      #     REDIS_PASSWORD: "Redis@123"
      #     MONGODB_HOST: "127.0.0.1"
      #     MONGODB_PORT: "27017"
      #     MONGODB_USERNAME: "user"
      #     MONGODB_PASSWORD: "User123"
      #     MONGODB_DATABASE: "sample_db"
      #   working-directory: source
      #   run: |
      #     pytest

      - name: Start FastAPI server
        working-directory: src
        run: |
          python start.py
